# Generated by Django 3.0.7 on 2020-06-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0003_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodel',
            old_name='username',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='password',
        ),
    ]
